### ISSUE TITLE
Problem with plmDCA

### ISSUE THREAD

**Issue by AnatolAicher** [dellacortelab/prospr#15]
When I try to `import plmDCA` in python, as described in the readme, I get an error:

> ```
> import plmDCA
> 
> Exception caught during initialization of Python interface. Details: Could not find an appropriate directory for MATLAB or the MATLAB runtime in LD_LIBRARY_PATH. Details: libmwmclmcrrt.so.9.4
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "home/prospr-master/potts-code/plmDCA/__init__.py", line 280, in <module>
>     _pir.get_paths_from_os()
> 
>   File "home/prospr-master/potts-code/plmDCA/__init__.py", line 182, in get_paths_from_os
>     self.path_var, file_to_find))
> 
> RuntimeError: Could not find an appropriate directory for MATLAB or the MATLAB runtime in LD_LIBRARY_PATH. Details: libmwmclmcrrt.so.9.4
> ```

I also realized that in my matlab directory I do not have an X11-directory, the one we are supposed to save as the environment variable XAPPLRESDIR.

Does anyone have a clue what could be the problem?

**Comment by Lorenzo360** [comment]
Did you add the path to you Matlab Runtime to your LD_LIBRARY_PATH variable? 

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/bin/glnxa64

You may have to adapt the path

**Comment by AnatolAicher** [comment]
I think I must have tried at least a dozen times doing that. Unfortunately it did not help.

**Comment by tianaix** [comment]
Same problem here, and I tried the same methods. Didn't work. 

Did anybody have suggestions regarding this? 

Thanks for any help

**Comment by maudagnotto** [comment]
I had the same problem and I solved by installing Matlab runtime and following the guideline in  7/otts-code/readme.txt. It works locally when I import the plmDCA but if I am running prosper from the docker it complains. Any suggestion is more than welcome :) 

I am also running the program by using singularity rather than docker since it is the only one supported by our IT service. 
This is the error that I got: 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Traceback (most recent call last):
  File "/opt/prospr.py", line 10, in <module>
    import pyfiglet
  File "/usr/local/lib/python3.6/site-packages/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 35, in <module>
    import plistlib
  File "/usr/lib64/python3.6/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/lib64/python3.6/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib64/python3.6/lib-dynload/pyexpat.cpython-36m-x86_64-linux-gnu.so: undefined symbol: XML_SetHashSalt
