### ISSUE TITLE
Missing hhmake Error?

### ISSUE THREAD

**Issue by KotaroTsuboyama** [dellacortelab/prospr#17]
According to this instruction https://github.com/dellacortelab/prospr/issues/12, I executed the following command to get pkl file from test2.seq, but I got the following error...
I already had databases for psiblast and hhblits, but hhmake seem to be missing. Should I install hhmake after doing "docker run prospr/prospr"?

Thank you in advance!

>sudo docker run -it -v /home/user/data:/data prospr/prospr build test2

[2020-04-18 01:57:09.576696] Running hhblits. . .
- 01:57:09.584 WARNING: Ignoring unknown option 
Psiblast database present and ready to use
[2020-04-18 01:57:09.589332] Building pssm file
[2020-04-18 01:59:28.209925] hhblits completed.
[2020-04-18 01:59:28.210090] hhmake running.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/prospr/hhblits.py", line 75, in run
    subprocess.run(hhmakeCommand)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] **No such file or directory: '/usr/local/bin/hhmake** -i /data/test2/test2.a3m -o /data/test2/test2.hhm': '/usr/local/bin/hhmake -i /data/test2/test2.a3m -o /data/test2/test2.hhm'
Warning: [psiblast] Query_1 T1019s2: Composition-based score adjustment conditioned on sequence properties and unconditional composition-based score adjustment is not supported with PSSMs, resetting to default value of standard composition-based statistics 
[2020-04-18 03:26:54.648224] . . .pssm file completed
[2020-04-18 03:26:54.676911] building final pkl sequence.
Traceback (most recent call last):
  File "/opt/prospr.py", line 125, in <module>
    build(args)
  File "/opt/prospr.py", line 111, in build
    s.build(args)
  File "/opt/prospr/io.py", line 37, in build
    s.hh()
  File "/opt/prospr/io.py", line 58, in hh
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/test2/test2.hhm'

**Comment by tyggna** [comment]
This error is ambiguous, but hhmake is included in the docker container.  My guess is that there's no "test2" directory in your local /home/user/data/ folder

**Comment by aiXander** [comment]
I'm having the same issue and I can confirm that the directory is present... Did anybody end up solving this issue?

**Comment by aiXander** [comment]
I found a solution for this issue by manually rebuilding the docker image with an updated version of BLAST:

- In the Dockerfile, change the installation of psi-BLAST to use the latest version: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast%2B/LATEST/
- manually rebuild the docker image and run it!
