### ISSUE TITLE
File is empty

### ISSUE THREAD

**Issue by skyungyong** [dellacortelab/prospr#20]
Hi all, 

I've encountered some problems while running the program with the following error messages. The MATLAB files indicated here (e.g., ischar.m) are empty. I am running Docker container, so I wonder this is the same for you guys. The file location is /usr/local/MATLAB/MATLAB_Runtime/v94/mcr/toolbox/matlab/strfun/ischar.m. Reinstalling MATLAB did not solve the problem. So I wonder whether you guys have any ideas. 

Thank you in advance! 

Singularity prospr_latest> python3 prospr/prospr.py build example1 -j 20
[2020-06-12 18:43:34.683504] Running hhblits. . .
[2020-06-12 18:43:38.570311] hhblits completed.
[2020-06-12 18:43:38.570358] hhmake running.
[2020-06-12 18:43:38.807135] hhmake completed.
[2020-06-12 18:43:38.807411] potts running.
inserting gaps...
Reformatted /prospr/data/example1/example1.a3m with 1146 sequences from a3m to a2m and written to file /prospr/data/example1/example1.a2m
Warning: The alias definition file '/prospr_latest/usr/bin/alias' has invalid syntax.
> In path (line 109)
  In addpath (line 96)
  In plmDCA_asymmetric (line 41)
File is empty
File is empty
File is empty
File is empty
File is empty
File is empty
File is empty
The file
   "/prospr_latest/usr/local/MATLAB/MATLAB_Runtime/v94/mcr/toolbox/matlab/strfun/ischar.m"
cannot be executed.

Error in fastaread (line 52)
Error in plmDCA_asymmetric>return_alignment (line 196)
Error in plmDCA_asymmetric (line 44)

Traceback (most recent call last):
  File "prospr/prospr.py", line 128, in <module>
    build(args)
  File "prospr/prospr.py", line 92, in build
    b.run()
  File "/prospr/prospr/hhblits.py", line 94, in run
    p.plmDCA_asymmetric(a2mf, matf, multiprocessing.cpu_count(), 1, nargout=0)
  File "/usr/local/MATLAB/MATLAB_Runtime/v94/toolbox/compiler_sdk/pysdk_py/matlab_pysdk/runtime/deployablefunc.py", line 80, in __call__
    nlhsWasSpecified, stdoutObj, stderrObj).result()
  File "/usr/local/MATLAB/MATLAB_Runtime/v94/toolbox/compiler_sdk/pysdk_py/matlab_pysdk/runtime/futureresult.py", line 135, in result
    raise e
  File "/usr/local/MATLAB/MATLAB_Runtime/v94/toolbox/compiler_sdk/pysdk_py/matlab_pysdk/runtime/futureresult.py", line 123, in result
    raise e
  File "/usr/local/MATLAB/MATLAB_Runtime/v94/toolbox/compiler_sdk/pysdk_py/matlab_pysdk/runtime/futureresult.py", line 113, in result
    self._nlhs, out=self._out, err=self._err)
matlab_pysdk.runtime.MatlabRuntimeError: An error occurred when evaluating the result from a function. Details:
  File /tmp/.mcrCache9.4/plmDCA0/toolbox/bioinfo/bioinfo/fastaread.m, line 52, in fastaread

  File /tmp/.mcrCache9.4/plmDCA0/plmDCA_asymm/plmDCA_asymmetric.m, line 196, in return_alignment

  File /tmp/.mcrCache9.4/plmDCA0/plmDCA_asymm/plmDCA_asymmetric.m, line 44, in plmDCA_asymmetric
The file
   "/prospr_latest/usr/local/MATLAB/MATLAB_Runtime/v94/mcr/toolbox/matlab/strfun/ischar.m"
cannot be executed.

File is empty
File is empty
File is empty
File is empty
The file
   "/prospr_latest/usr/local/MATLAB/MATLAB_Runtime/v94/mcr/toolbox/matlab/graphics/ishghandle.m"
cannot be executed.

Error in allchild (line 23)
Error using mclkillallfigures
The file
   "prospr_latest/usr/local/MATLAB/MATLAB_Runtime/v94/mcr/toolbox/matlab/graphics/ishghandle.m"
cannot be executed.

File is empty
The file
   "prospr_latest/usr/local/MATLAB/MATLAB_Runtime/v94/mcr/toolbox/matlab/lang/warning.m"
cannot be executed.

**Comment by tyggna** [comment]
We're in the process of removing the MATLAB dependency all-together.  This will be fixed in our next release.
